version: '3.9'
services:
  api:
    build:
      context: ../../services/api
      dockerfile: Dockerfile
    image: beterminal/api:prod
    environment:
      - PORT=4000
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - '4000'
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
      # TLS termination recommended via a separate reverse proxy/ingress; or mount certs and map 443
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: unless-stopped
